# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - 'master'

# the type of VM you are going to use

pool:
  vmImage: 'ubuntu-latest'

# Watch for PRs
pr: none

# the sequential steps to follow - build, run, test, deploy, etc...
stages: # This stage will build the project
  - stage:
    jobs:
      - job: 'build'
        steps:
          - script: dotnet build 'RPC_Game/RPC_Game.sln'
      
